// Major Arcana — 22 cards, bilingual (EN + TH)
const TAROT_DECK = [
  { n: 0, emoji: "🃏",
    name: { en: "The Fool", th: "คนโง่" },
    up: { en: "A fresh beginning, the courage to set out, and the bright freedom of an open heart.",
          th: "การเริ่มต้นใหม่ ความกล้าออกเดินทาง อิสระและความไร้เดียงสาที่สดใส" },
    rev: { en: "Hesitation, fear of change, or a choice made without enough thought.",
           th: "ความลังเล กลัวการเปลี่ยนแปลง ตัดสินใจอย่างไม่รอบคอบ" },
    kw: { en: "Beginnings • Adventure • Freedom", th: "เริ่มต้น • ผจญภัย • อิสระ" } },
  { n: 1, emoji: "🪄",
    name: { en: "The Magician", th: "นักมายากล" },
    up: { en: "You hold every tool and talent you need. Step forward and make it real.",
          th: "คุณมีพลังและทรัพยากรครบพร้อมที่จะทำให้สำเร็จ ลงมือเลย" },
    rev: { en: "Talent misdirected, or a confidence that quietly deceives the self.",
           th: "ใช้ความสามารถผิดทาง ความมั่นใจที่หลอกตัวเอง" },
    kw: { en: "Power • Opportunity • Action", th: "พลัง • โอกาส • ลงมือทำ" } },
  { n: 2, emoji: "🌙",
    name: { en: "The High Priestess", th: "นักบวชหญิง" },
    up: { en: "Trust your intuition. A hidden truth is preparing to reveal itself.",
          th: "เชื่อสัญชาตญาณของตัวเอง ความลับกำลังจะเผยออกมา" },
    rev: { en: "An inner voice ignored, or knowledge being kept from view.",
           th: "ละเลยเสียงในใจ ข้อมูลถูกปิดบัง" },
    kw: { en: "Intuition • Mystery • Wisdom", th: "สัญชาตญาณ • ความลับ • ปัญญา" } },
  { n: 3, emoji: "🌷",
    name: { en: "The Empress", th: "จักรพรรดินี" },
    up: { en: "Abundance, love, and growth. Something lovely is coming into bloom.",
          th: "ความอุดมสมบูรณ์ ความรักและการเติบโต สิ่งดีๆ กำลังผลิบาน" },
    rev: { en: "A creative block, or a gentle reminder to care for yourself.",
           th: "ติดขัดด้านความคิดสร้างสรรค์ ละเลยการดูแลตัวเอง" },
    kw: { en: "Abundance • Love • Growth", th: "อุดมสมบูรณ์ • ความรัก • เติบโต" } },
  { n: 4, emoji: "👑",
    name: { en: "The Emperor", th: "จักรพรรดิ" },
    up: { en: "Stability, discipline, and steady, grounded leadership.",
          th: "ความมั่นคง ระเบียบวินัย และการเป็นผู้นำที่หนักแน่น" },
    rev: { en: "Stubbornness, over-control, or a lack of flexibility.",
           th: "ดื้อรั้น ควบคุมมากเกินไป ขาดความยืดหยุ่น" },
    kw: { en: "Structure • Leadership • Stability", th: "มั่นคง • ผู้นำ • โครงสร้าง" } },
  { n: 5, emoji: "📜",
    name: { en: "The Hierophant", th: "พระสันตะปาปา" },
    up: { en: "Guidance from the wise, and learning rooted in tradition.",
          th: "คำแนะนำจากผู้รู้ ขนบประเพณีและการเรียนรู้ที่มั่นคง" },
    rev: { en: "Questioning the rules and finding your own free path.",
           th: "ท้าทายกฎเกณฑ์ หาทางของตัวเองอย่างอิสระ" },
    kw: { en: "Wisdom • Tradition • Mentor", th: "ปัญญา • ประเพณี • ครู" } },
  { n: 6, emoji: "💕",
    name: { en: "The Lovers", th: "คู่รัก" },
    up: { en: "A harmonious love, and a choice made truly from the heart.",
          th: "ความรักที่กลมเกลียว การเลือกที่มาจากหัวใจ ความสัมพันธ์ที่ดี" },
    rev: { en: "Disharmony, or a decision that quietly works against your own heart.",
           th: "ความไม่ลงรอย ตัดสินใจขัดกับใจตัวเอง" },
    kw: { en: "Love • Choice • Union", th: "ความรัก • ทางเลือก • ผูกพัน" } },
  { n: 7, emoji: "🐎",
    name: { en: "The Chariot", th: "ราชรถ" },
    up: { en: "Victory through determination. Move forward with a clear purpose.",
          th: "ชัยชนะด้วยความมุ่งมั่น ก้าวไปข้างหน้าอย่างมีเป้าหมาย" },
    rev: { en: "A loss of direction, or energy scattered without focus.",
           th: "ขาดทิศทาง พลังที่กระจัดกระจาย ควบคุมไม่ได้" },
    kw: { en: "Victory • Drive • Progress", th: "ชัยชนะ • มุ่งมั่น • ก้าวหน้า" } },
  { n: 8, emoji: "🦁",
    name: { en: "Strength", th: "พลัง" },
    up: { en: "Gentle courage. Patience and the quiet power to master yourself.",
          th: "ความกล้าหาญที่อ่อนโยน อดทนและเอาชนะใจตัวเองได้" },
    rev: { en: "Self-doubt, or letting emotion take the lead.",
           th: "ความไม่มั่นใจ ปล่อยให้อารมณ์ครอบงำ" },
    kw: { en: "Courage • Patience • Compassion", th: "กล้าหาญ • อดทน • อ่อนโยน" } },
  { n: 9, emoji: "🏮",
    name: { en: "The Hermit", th: "ฤๅษี" },
    up: { en: "A time of reflection. The answer you seek is found within.",
          th: "ช่วงเวลาแห่งการทบทวนตัวเอง ค้นพบคำตอบจากภายใน" },
    rev: { en: "Too much solitude, or withdrawing too far from others.",
           th: "โดดเดี่ยวเกินไป หลีกหนีจากผู้คน" },
    kw: { en: "Reflection • Wisdom • Solitude", th: "ทบทวน • ปัญญา • ภายใน" } },
  { n: 10, emoji: "🎡",
    name: { en: "Wheel of Fortune", th: "วงล้อแห่งโชคชะตา" },
    up: { en: "Fortune turns in your favor. A welcome turning point arrives.",
          th: "โชคหมุนเข้าข้าง จุดเปลี่ยนที่ดีกำลังมาถึง" },
    rev: { en: "A passing run of bad luck — a cycle that asks for patience.",
           th: "โชคไม่เข้าข้างชั่วคราว วัฏจักรที่ต้องอดทนรอ" },
    kw: { en: "Destiny • Turning Point • Cycles", th: "โชคชะตา • จุดเปลี่ยน • วัฏจักร" } },
  { n: 11, emoji: "⚖️",
    name: { en: "Justice", th: "ความยุติธรรม" },
    up: { en: "Fairness and balance. A just outcome, and the truth coming to light.",
          th: "ความเที่ยงธรรม ผลลัพธ์ที่ยุติธรรม ความจริงปรากฏ" },
    rev: { en: "Unfairness, or avoiding responsibility.",
           th: "ความไม่เป็นธรรม หลีกเลี่ยงความรับผิดชอบ" },
    kw: { en: "Justice • Balance • Truth", th: "ยุติธรรม • สมดุล • ความจริง" } },
  { n: 12, emoji: "🙃",
    name: { en: "The Hanged Man", th: "คนแขวนคอ" },
    up: { en: "See things from a new angle. Release, and wait with understanding.",
          th: "มองในมุมใหม่ ปล่อยวางและรอคอยอย่างเข้าใจ" },
    rev: { en: "Refusing to shift, or staying stuck in place.",
           th: "ดื้อที่จะไม่เปลี่ยน ติดอยู่กับที่" },
    kw: { en: "New Perspective • Surrender • Pause", th: "มุมมองใหม่ • ปล่อยวาง • รอคอย" } },
  { n: 13, emoji: "🦋",
    name: { en: "Death", th: "ความตาย" },
    up: { en: "An ending that makes way for a new start — a meaningful transformation.",
          th: "การสิ้นสุดเพื่อเริ่มใหม่ การเปลี่ยนแปลงครั้งใหญ่ที่ดี" },
    rev: { en: "Resisting change, or clinging to what has already passed.",
           th: "ต้านการเปลี่ยนแปลง ยึดติดกับสิ่งเดิม" },
    kw: { en: "Transformation • Renewal • Release", th: "เปลี่ยนแปลง • เริ่มใหม่ • ปล่อย" } },
  { n: 14, emoji: "🍵",
    name: { en: "Temperance", th: "ความพอดี" },
    up: { en: "Balance and patience, and the gentle art of finding the middle way.",
          th: "ความสมดุล ความอดทนและการประนีประนอมอย่างนุ่มนวล" },
    rev: { en: "Imbalance, impatience, or taking things to excess.",
           th: "ขาดสมดุล ใจร้อน ทำอะไรเกินพอดี" },
    kw: { en: "Balance • Moderation • Patience", th: "สมดุล • พอดี • อดทน" } },
  { n: 15, emoji: "🔗",
    name: { en: "The Devil", th: "ปีศาจ" },
    up: { en: "Beware the bonds — a craving or habit that may be holding you.",
          th: "ระวังพันธนาการ ความหลงใหลหรือนิสัยที่ผูกมัดคุณไว้" },
    rev: { en: "Breaking free of what holds you back, returning to your freedom.",
           th: "ปลดปล่อยตัวเองจากสิ่งที่ฉุดรั้ง คืนสู่อิสระ" },
    kw: { en: "Bondage • Release • Attachment", th: "พันธนาการ • ปลดปล่อย • ยึดติด" } },
  { n: 16, emoji: "⚡",
    name: { en: "The Tower", th: "หอคอย" },
    up: { en: "Sudden change. A truth that shakes the ground, yet sets you free.",
          th: "การเปลี่ยนแปลงฉับพลัน ความจริงที่สั่นคลอนแต่ปลดปล่อย" },
    rev: { en: "Avoiding a crisis, or a needed change held off too long.",
           th: "หลีกเลี่ยงวิกฤต ความเปลี่ยนแปลงที่ยื้อไว้" },
    kw: { en: "Upheaval • Awakening • Release", th: "พลิกผัน • ตื่นรู้ • ปลดปล่อย" } },
  { n: 17, emoji: "⭐",
    name: { en: "The Star", th: "ดวงดาว" },
    up: { en: "Hope and inspiration. Healing, and renewed faith in what lies ahead.",
          th: "ความหวังและแรงบันดาลใจ เยียวยาและศรัทธาในอนาคต" },
    rev: { en: "A passing loss of hope, or faltering faith in yourself.",
           th: "หมดหวังชั่วคราว ขาดศรัทธาในตัวเอง" },
    kw: { en: "Hope • Healing • Inspiration", th: "ความหวัง • เยียวยา • แรงบันดาลใจ" } },
  { n: 18, emoji: "🌕",
    name: { en: "The Moon", th: "พระจันทร์" },
    up: { en: "Deep feelings and dreams, and things not yet clear — trust your instinct.",
          th: "ความรู้สึกลึกๆ ความฝันและสิ่งที่ยังไม่ชัดเจน เชื่อสัญชาตญาณ" },
    rev: { en: "Confusion lifting, and the truth beginning to show.",
           th: "ความสับสนคลี่คลาย ความจริงเริ่มกระจ่าง" },
    kw: { en: "Dreams • Mystery • Intuition", th: "ความฝัน • ลึกลับ • สัญชาตญาณ" } },
  { n: 19, emoji: "☀️",
    name: { en: "The Sun", th: "พระอาทิตย์" },
    up: { en: "Joy, success, and radiant positivity. A bright and shining season.",
          th: "ความสุข ความสำเร็จ และพลังบวกที่เปล่งประกาย ช่วงเวลาที่สดใส" },
    rev: { en: "Joy briefly clouded, or optimism stretched a little thin.",
           th: "ความสุขที่ถูกบดบังชั่วคราว มองโลกแง่ดีเกินไป" },
    kw: { en: "Joy • Success • Radiance", th: "ความสุข • สำเร็จ • สดใส" } },
  { n: 20, emoji: "🎺",
    name: { en: "Judgement", th: "การพิพากษา" },
    up: { en: "An awakening. Release the past and step into a new chapter of life.",
          th: "การตื่นรู้ ปลดปล่อยอดีตและก้าวสู่บทใหม่ของชีวิต" },
    rev: { en: "Judging yourself harshly, or hesitating to move on.",
           th: "ตัดสินตัวเองรุนแรง ลังเลที่จะก้าวต่อ" },
    kw: { en: "Awakening • Renewal • Release", th: "ตื่นรู้ • เริ่มใหม่ • ปลดปล่อย" } },
  { n: 21, emoji: "🌍",
    name: { en: "The World", th: "โลก" },
    up: { en: "Completion and fulfilment. A cycle closing beautifully.",
          th: "ความสมบูรณ์ การบรรลุเป้าหมาย วงจรที่จบลงอย่างสวยงาม" },
    rev: { en: "So close to done — a little more patience is all it asks.",
           th: "ใกล้สำเร็จแต่ยังขาดอีกนิด อดทนอีกหน่อย" },
    kw: { en: "Completion • Fulfilment • Achievement", th: "สำเร็จ • สมบูรณ์ • บรรลุ" } }
];

// ป้ายตำแหน่งไพ่ตามรูปแบบและภาษา
const SPREAD_LABELS = {
  1: { en: ["Your Reading"], th: ["คำทำนายของคุณ"] },
  3: { en: ["Past", "Present", "Future"], th: ["อดีต", "ปัจจุบัน", "อนาคต"] }
};

// ข้อความ UI ของหน้าเว็บ
const UI_TEXT = {
  en: {
    title: "Luna",
    kicker: "˚ ✦ ˚ moonlit fortunes ˚ ✦ ˚",
    subtitle: "Hold your question gently in mind, then let the cards guide you.",
    deckTarot: "🔮 Tarot",
    deckPoker: "🂠 Playing Cards",
    titlePoker: "Luna",
    subtitlePoker: "A 34-card deck of fate — shuffle, breathe, and draw your fortune.",
    mode1: "Single Card",
    mode3: "Three Cards",
    hint1: "A single card for the question of the day.",
    hint3: "Three cards telling a story: Past · Present · Future.",
    draw: "Shuffle Cards",
    pickRemaining: "Tap the deck to choose {n} more ✦",
    pickDone: "Your cards are chosen ✦ scroll down to read them",
    pickAria: "Face-down card — tap to choose",
    tapReveal: "Tap to reveal",
    upright: "Upright ✦",
    reversed: "Reversed ⟲",
    footer: "For entertainment purposes only · May your day be bright ♡",
    aiButton: "🔮 Interpret with AI",
    aiBoxTitle: "AI Fortune Reading",
    aiThinking: "Reading your cards",
    aiNoCards: "Draw your cards first, then let the AI read them ✨",
    aiError: "Something went wrong — check your API key and try again.",
    settingsHeading: "Settings",
    themeLabel: "Dark theme",
    modelLabel: "AI model",
    modelHints: {
      "claude-haiku-4-5": "Fastest & most affordable",
      "claude-sonnet-4-6": "Balanced speed & depth",
      "claude-opus-4-8": "Most capable (pricier)"
    },
    aiKeyTitle: "Claude API key",
    aiKeyNote: "Stored only in this browser. Used to call Claude directly. Never share a key you use elsewhere.",
    aiKeyPlaceholder: "sk-ant-…",
    aiKeySave: "Save key",
    aiKeyChange: "Change API key",
    aiKeyRemove: "Remove key",
    aiKeySaved: "✓ API key saved",
    aiKeyNone: "No API key saved yet",
    aiReadAgain: "Read again"
  },
  th: {
    title: "Luna",
    kicker: "˚ ✦ ˚ คำทำนายใต้แสงจันทร์ ˚ ✦ ˚",
    subtitle: "ตั้งใจถามคำถามในใจ แล้วปล่อยให้ไพ่นำทางคุณ",
    deckTarot: "🔮 ไพ่ทาโร่",
    deckPoker: "🂠 ไพ่ป๊อก",
    titlePoker: "Luna",
    subtitlePoker: "สำรับแห่งโชคชะตา 34 ใบ สับไพ่ หายใจเข้า แล้วสุ่มดวงของคุณ",
    mode1: "ไพ่ 1 ใบ",
    mode3: "ไพ่ 3 ใบ",
    hint1: "ไพ่ใบเดียวสำหรับคำถามของวันนี้",
    hint3: "ไพ่สามใบเล่าเรื่อง อดีต · ปัจจุบัน · อนาคต",
    draw: "สับไพ่",
    pickRemaining: "แตะกองไพ่เพื่อเลือกอีก {n} ใบ ✦",
    pickDone: "เลือกไพ่ครบแล้ว ✦ เลื่อนลงอ่านคำทำนายได้เลย",
    pickAria: "ไพ่คว่ำ — แตะเพื่อเลือก",
    tapReveal: "แตะเพื่อเปิด",
    upright: "ไพ่ตั้ง ✦",
    reversed: "ไพ่กลับหัว ⟲",
    footer: "ทำขึ้นเพื่อความบันเทิงเท่านั้น · ขอให้เป็นวันที่ดีนะ ♡",
    aiButton: "🔮 ให้ AI ทำนาย",
    aiBoxTitle: "คำทำนายจาก AI",
    aiThinking: "กำลังอ่านไพ่ให้คุณ",
    aiNoCards: "เปิดไพ่ก่อนนะคะ แล้วค่อยให้ AI ทำนาย ✨",
    aiError: "เกิดข้อผิดพลาด — ตรวจสอบ API key แล้วลองใหม่อีกครั้งนะคะ",
    settingsHeading: "ตั้งค่า",
    themeLabel: "ธีมมืด",
    modelLabel: "โมเดล AI",
    modelHints: {
      "claude-haiku-4-5": "เร็วและประหยัดที่สุด",
      "claude-sonnet-4-6": "สมดุลความเร็วกับความลึก",
      "claude-opus-4-8": "เก่งที่สุด (ราคาสูงกว่า)"
    },
    aiKeyTitle: "API key ของ Claude",
    aiKeyNote: "เก็บไว้ในเบราว์เซอร์นี้เท่านั้น ใช้เรียก Claude โดยตรง อย่าใช้ key ที่ใช้ที่อื่นร่วมกัน",
    aiKeyPlaceholder: "sk-ant-…",
    aiKeySave: "บันทึก key",
    aiKeyChange: "เปลี่ยน API key",
    aiKeyRemove: "ลบ key",
    aiKeySaved: "✓ บันทึก API key แล้ว",
    aiKeyNone: "ยังไม่ได้บันทึก API key",
    aiReadAgain: "ทำนายอีกครั้ง"
  }
};
